### ISSUE TITLE
Skybox shows seams

### ISSUE THREAD

**Issue by willcrichton** [jomala/bevy_skybox#2]
I'm testing out bevy_skybox with the provided sample images, and I can observe seams at the top of the box (which I assume is not intentional?). 

<img width="1392" alt="Screen Shot 2021-01-27 at 10 46 56 AM" src="https://user-images.githubusercontent.com/663326/106016027-e8501500-6073-11eb-90b7-ddb1fc5c8952.png">

<img width="1392" alt="Screen Shot 2021-01-27 at 10 48 22 AM" src="https://user-images.githubusercontent.com/663326/106016195-0f0e4b80-6074-11eb-8938-01be53ed0ffe.png">

**Comment by jomala** [comment]
The image sources do not have sharp right angles. If you use a better image you should avoid the seems.

**Comment by willcrichton** [comment]
Ok thanks just checking.
